import{a as L,S as b,i as c}from"./assets/vendor-95dc692e.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))p(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const l of s.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&p(l)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function p(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const v="21675808-1204a02bf0a9f212ef3ae3caa",q="https://pixabay.com/api/";async function f(r,e){try{return(await L.get(q,{params:{q:r,page:e,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0,key:v}})).data}catch(o){console.error(o)}}function y(r){return r.map(e=>`<li class="gallery-item">
                <a class="gallery-link" href='${e.largeImageURL}'>
                  <img class="gallery-image" src='${e.webformatURL}' alt='${e.tags}' />
                </a>
                <div class="stats">
                  <p><span>Likes</span>${e.likes}</p>
                  <p><span>Views</span>${e.views}</p>
                  <p><span>Comments</span>${e.comments}</p>
                  <p><span>Downloads</span>${e.downloads}</p>
                </div>
              </li>`).join("")}const w=document.querySelector(".form"),d=document.querySelector(".gallery"),g=document.querySelector(".loader"),i=document.querySelector(".load-more");w.addEventListener("submit",S);i.addEventListener("click",P);const h=new b(".gallery-link",{captionsData:"alt",captionDelay:250,overlay:!0,overlayOpacity:.7});let a=1,n="";async function S(r){if(r.preventDefault(),m(),i.classList.add("is-hidden"),d.innerHTML="",a=1,n=r.target.queryInput.value.trim(),n!=="")try{const e=await f(n,a);if(e.hits.length===0)return u(),c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});d.innerHTML=y(e.hits),e.total>15&&i.classList.remove("is-hidden"),h.refresh(),r.target.queryInput.value=""}catch(e){console.log(e)}else c.info({message:'Please, enter a query, for example "cats"',position:"topLeft"});u()}async function P(){m(),a+=1;try{const r=await f(n,a),e=Math.ceil(r.total/15);d.insertAdjacentHTML("beforeend",y(r.hits)),h.refresh();const{height:o}=document.querySelector(".gallery").firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"}),e===a&&(i.classList.add("is-hidden"),c.info({message:"We're sorry, but you've reached the end of search results.",position:"topLeft"}))}catch(r){console.log(r)}u()}function m(){g.classList.remove("is-hidden")}function u(){g.classList.add("is-hidden")}
//# sourceMappingURL=commonHelpers.js.map
